version: 0.2
phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws cloudformation package --template template.yaml --s3-bucket "" --output-template post-template.yaml
artifacts:
  files:
    - post-template.yaml
