version: 0.2
phases:
  install:
    commands:
      - npm install -g yarn
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
artifacts:
    files:
      - './dist/**/*'
      - './template.yaml'
