AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mossypad api.
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: moussypad-api
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./dist
      Role: !Ref LambdaTrustRole
  LambdaTrustRole:
    Type: AWS::IAM::Role
    RoleName: moussypad-api-lambda-service-role
    AssumeRolePolicyDocument:
      Statement:
      - Effect: Allow
        Principal:
          Service: [lambda.amazonaws.com]
        Action: sts:AssumeRole
    Path: /
  LambdaRolePolicy:
    Type: AWS::IAM::Policy
    DependsOn: LambdaTrustRole
    Properties:
      PolicyName: AWSLambdaBasicExecutionRole
