AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mossypad api.
Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: moussypad-api
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./dist
      Role: arn:aws:iam::146676994108:role/moussypad-api-lambda-service-role